#配置端口
server:
  port: 8150
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.60.2.175:3306/care?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    #环境设置:dev test prod
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-ucenter
  redis:
    host: 10.60.2.187
    port: 6380
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: gbcom@gidata@123

mybatis-plus:
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
  mapper-locations: classpath:com/xzq/serviceUcenter/mapper/xml/*.xml
logging:
  config: classpath:logging/logback-spring.xml
#开启熔断机制
feign:
  hystrix:
    enabled: true
# 设置hystrix超时时间，默认1000ms
hystrix:
  metrics:
    polling-interval-ms: 6000
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://guli.shop/api/ucenter/wx/callback
